name: CI Pipeline

# Указываем события, которые должны запускать пайплайн
on:
  push:
    branches:
      - main   # Запускать на пуши в ветку main
  pull_request:
    branches:
      - main   # Запускать при создании pull request'ов в ветку main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install flake8
        run: |
          pip install flake8  # Установка flake8
      - name: Run flake8
        run: |
          flake8 . --max-line-length=120

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add the project directory to PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
